/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppTenantsRouteImport } from './routes/_app/tenants'
import { Route as AppLogsRouteImport } from './routes/_app/logs'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppTenantsIndexRouteImport } from './routes/_app/tenants.index'
import { Route as AppTenantsIdRouteImport } from './routes/_app/tenants.$id'
import { Route as AppSupportJobsRouteImport } from './routes/_app/support.jobs'
import { Route as AppSupportImpersonationRouteImport } from './routes/_app/support.impersonation'
import { Route as AppSupportDiagnosticsRouteImport } from './routes/_app/support.diagnostics'
import { Route as AppSettingsModulesRouteImport } from './routes/_app/settings.modules'
import { Route as AppSettingsGlobalRouteImport } from './routes/_app/settings.global'
import { Route as AppSettingsModulesPayrollRouteImport } from './routes/_app/settings.modules.payroll'
import { Route as AppSettingsModulesManpowerRouteImport } from './routes/_app/settings.modules.manpower'
import { Route as AppSettingsModulesIppmsRouteImport } from './routes/_app/settings.modules.ippms'
import { Route as AppAdminOrgsOrgIdUsersRouteImport } from './routes/_app/admin.orgs.$orgId.users'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTenantsRoute = AppTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsRoute = AppLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppTenantsIndexRoute = AppTenantsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTenantsRoute,
} as any)
const AppTenantsIdRoute = AppTenantsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppTenantsRoute,
} as any)
const AppSupportJobsRoute = AppSupportJobsRouteImport.update({
  id: '/support/jobs',
  path: '/support/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportImpersonationRoute = AppSupportImpersonationRouteImport.update({
  id: '/support/impersonation',
  path: '/support/impersonation',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportDiagnosticsRoute = AppSupportDiagnosticsRouteImport.update({
  id: '/support/diagnostics',
  path: '/support/diagnostics',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsModulesRoute = AppSettingsModulesRouteImport.update({
  id: '/settings/modules',
  path: '/settings/modules',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsGlobalRoute = AppSettingsGlobalRouteImport.update({
  id: '/settings/global',
  path: '/settings/global',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsModulesPayrollRoute =
  AppSettingsModulesPayrollRouteImport.update({
    id: '/payroll',
    path: '/payroll',
    getParentRoute: () => AppSettingsModulesRoute,
  } as any)
const AppSettingsModulesManpowerRoute =
  AppSettingsModulesManpowerRouteImport.update({
    id: '/manpower',
    path: '/manpower',
    getParentRoute: () => AppSettingsModulesRoute,
  } as any)
const AppSettingsModulesIppmsRoute = AppSettingsModulesIppmsRouteImport.update({
  id: '/ippms',
  path: '/ippms',
  getParentRoute: () => AppSettingsModulesRoute,
} as any)
const AppAdminOrgsOrgIdUsersRoute = AppAdminOrgsOrgIdUsersRouteImport.update({
  id: '/admin/orgs/$orgId/users',
  path: '/admin/orgs/$orgId/users',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/logs': typeof AppLogsRoute
  '/tenants': typeof AppTenantsRouteWithChildren
  '/users': typeof AppUsersRoute
  '/': typeof AppIndexRoute
  '/settings/global': typeof AppSettingsGlobalRoute
  '/settings/modules': typeof AppSettingsModulesRouteWithChildren
  '/support/diagnostics': typeof AppSupportDiagnosticsRoute
  '/support/impersonation': typeof AppSupportImpersonationRoute
  '/support/jobs': typeof AppSupportJobsRoute
  '/tenants/$id': typeof AppTenantsIdRoute
  '/tenants/': typeof AppTenantsIndexRoute
  '/settings/modules/ippms': typeof AppSettingsModulesIppmsRoute
  '/settings/modules/manpower': typeof AppSettingsModulesManpowerRoute
  '/settings/modules/payroll': typeof AppSettingsModulesPayrollRoute
  '/admin/orgs/$orgId/users': typeof AppAdminOrgsOrgIdUsersRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/logs': typeof AppLogsRoute
  '/users': typeof AppUsersRoute
  '/': typeof AppIndexRoute
  '/settings/global': typeof AppSettingsGlobalRoute
  '/settings/modules': typeof AppSettingsModulesRouteWithChildren
  '/support/diagnostics': typeof AppSupportDiagnosticsRoute
  '/support/impersonation': typeof AppSupportImpersonationRoute
  '/support/jobs': typeof AppSupportJobsRoute
  '/tenants/$id': typeof AppTenantsIdRoute
  '/tenants': typeof AppTenantsIndexRoute
  '/settings/modules/ippms': typeof AppSettingsModulesIppmsRoute
  '/settings/modules/manpower': typeof AppSettingsModulesManpowerRoute
  '/settings/modules/payroll': typeof AppSettingsModulesPayrollRoute
  '/admin/orgs/$orgId/users': typeof AppAdminOrgsOrgIdUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/logs': typeof AppLogsRoute
  '/_app/tenants': typeof AppTenantsRouteWithChildren
  '/_app/users': typeof AppUsersRoute
  '/_app/': typeof AppIndexRoute
  '/_app/settings/global': typeof AppSettingsGlobalRoute
  '/_app/settings/modules': typeof AppSettingsModulesRouteWithChildren
  '/_app/support/diagnostics': typeof AppSupportDiagnosticsRoute
  '/_app/support/impersonation': typeof AppSupportImpersonationRoute
  '/_app/support/jobs': typeof AppSupportJobsRoute
  '/_app/tenants/$id': typeof AppTenantsIdRoute
  '/_app/tenants/': typeof AppTenantsIndexRoute
  '/_app/settings/modules/ippms': typeof AppSettingsModulesIppmsRoute
  '/_app/settings/modules/manpower': typeof AppSettingsModulesManpowerRoute
  '/_app/settings/modules/payroll': typeof AppSettingsModulesPayrollRoute
  '/_app/admin/orgs/$orgId/users': typeof AppAdminOrgsOrgIdUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/dashboard'
    | '/logs'
    | '/tenants'
    | '/users'
    | '/'
    | '/settings/global'
    | '/settings/modules'
    | '/support/diagnostics'
    | '/support/impersonation'
    | '/support/jobs'
    | '/tenants/$id'
    | '/tenants/'
    | '/settings/modules/ippms'
    | '/settings/modules/manpower'
    | '/settings/modules/payroll'
    | '/admin/orgs/$orgId/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/dashboard'
    | '/logs'
    | '/users'
    | '/'
    | '/settings/global'
    | '/settings/modules'
    | '/support/diagnostics'
    | '/support/impersonation'
    | '/support/jobs'
    | '/tenants/$id'
    | '/tenants'
    | '/settings/modules/ippms'
    | '/settings/modules/manpower'
    | '/settings/modules/payroll'
    | '/admin/orgs/$orgId/users'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/dashboard'
    | '/_app/logs'
    | '/_app/tenants'
    | '/_app/users'
    | '/_app/'
    | '/_app/settings/global'
    | '/_app/settings/modules'
    | '/_app/support/diagnostics'
    | '/_app/support/impersonation'
    | '/_app/support/jobs'
    | '/_app/tenants/$id'
    | '/_app/tenants/'
    | '/_app/settings/modules/ippms'
    | '/_app/settings/modules/manpower'
    | '/_app/settings/modules/payroll'
    | '/_app/admin/orgs/$orgId/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tenants': {
      id: '/_app/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof AppTenantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logs': {
      id: '/_app/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AppLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tenants/': {
      id: '/_app/tenants/'
      path: '/'
      fullPath: '/tenants/'
      preLoaderRoute: typeof AppTenantsIndexRouteImport
      parentRoute: typeof AppTenantsRoute
    }
    '/_app/tenants/$id': {
      id: '/_app/tenants/$id'
      path: '/$id'
      fullPath: '/tenants/$id'
      preLoaderRoute: typeof AppTenantsIdRouteImport
      parentRoute: typeof AppTenantsRoute
    }
    '/_app/support/jobs': {
      id: '/_app/support/jobs'
      path: '/support/jobs'
      fullPath: '/support/jobs'
      preLoaderRoute: typeof AppSupportJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/support/impersonation': {
      id: '/_app/support/impersonation'
      path: '/support/impersonation'
      fullPath: '/support/impersonation'
      preLoaderRoute: typeof AppSupportImpersonationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/support/diagnostics': {
      id: '/_app/support/diagnostics'
      path: '/support/diagnostics'
      fullPath: '/support/diagnostics'
      preLoaderRoute: typeof AppSupportDiagnosticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/modules': {
      id: '/_app/settings/modules'
      path: '/settings/modules'
      fullPath: '/settings/modules'
      preLoaderRoute: typeof AppSettingsModulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/global': {
      id: '/_app/settings/global'
      path: '/settings/global'
      fullPath: '/settings/global'
      preLoaderRoute: typeof AppSettingsGlobalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/modules/payroll': {
      id: '/_app/settings/modules/payroll'
      path: '/payroll'
      fullPath: '/settings/modules/payroll'
      preLoaderRoute: typeof AppSettingsModulesPayrollRouteImport
      parentRoute: typeof AppSettingsModulesRoute
    }
    '/_app/settings/modules/manpower': {
      id: '/_app/settings/modules/manpower'
      path: '/manpower'
      fullPath: '/settings/modules/manpower'
      preLoaderRoute: typeof AppSettingsModulesManpowerRouteImport
      parentRoute: typeof AppSettingsModulesRoute
    }
    '/_app/settings/modules/ippms': {
      id: '/_app/settings/modules/ippms'
      path: '/ippms'
      fullPath: '/settings/modules/ippms'
      preLoaderRoute: typeof AppSettingsModulesIppmsRouteImport
      parentRoute: typeof AppSettingsModulesRoute
    }
    '/_app/admin/orgs/$orgId/users': {
      id: '/_app/admin/orgs/$orgId/users'
      path: '/admin/orgs/$orgId/users'
      fullPath: '/admin/orgs/$orgId/users'
      preLoaderRoute: typeof AppAdminOrgsOrgIdUsersRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppTenantsRouteChildren {
  AppTenantsIdRoute: typeof AppTenantsIdRoute
  AppTenantsIndexRoute: typeof AppTenantsIndexRoute
}

const AppTenantsRouteChildren: AppTenantsRouteChildren = {
  AppTenantsIdRoute: AppTenantsIdRoute,
  AppTenantsIndexRoute: AppTenantsIndexRoute,
}

const AppTenantsRouteWithChildren = AppTenantsRoute._addFileChildren(
  AppTenantsRouteChildren,
)

interface AppSettingsModulesRouteChildren {
  AppSettingsModulesIppmsRoute: typeof AppSettingsModulesIppmsRoute
  AppSettingsModulesManpowerRoute: typeof AppSettingsModulesManpowerRoute
  AppSettingsModulesPayrollRoute: typeof AppSettingsModulesPayrollRoute
}

const AppSettingsModulesRouteChildren: AppSettingsModulesRouteChildren = {
  AppSettingsModulesIppmsRoute: AppSettingsModulesIppmsRoute,
  AppSettingsModulesManpowerRoute: AppSettingsModulesManpowerRoute,
  AppSettingsModulesPayrollRoute: AppSettingsModulesPayrollRoute,
}

const AppSettingsModulesRouteWithChildren =
  AppSettingsModulesRoute._addFileChildren(AppSettingsModulesRouteChildren)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppLogsRoute: typeof AppLogsRoute
  AppTenantsRoute: typeof AppTenantsRouteWithChildren
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSettingsGlobalRoute: typeof AppSettingsGlobalRoute
  AppSettingsModulesRoute: typeof AppSettingsModulesRouteWithChildren
  AppSupportDiagnosticsRoute: typeof AppSupportDiagnosticsRoute
  AppSupportImpersonationRoute: typeof AppSupportImpersonationRoute
  AppSupportJobsRoute: typeof AppSupportJobsRoute
  AppAdminOrgsOrgIdUsersRoute: typeof AppAdminOrgsOrgIdUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppLogsRoute: AppLogsRoute,
  AppTenantsRoute: AppTenantsRouteWithChildren,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
  AppSettingsGlobalRoute: AppSettingsGlobalRoute,
  AppSettingsModulesRoute: AppSettingsModulesRouteWithChildren,
  AppSupportDiagnosticsRoute: AppSupportDiagnosticsRoute,
  AppSupportImpersonationRoute: AppSupportImpersonationRoute,
  AppSupportJobsRoute: AppSupportJobsRoute,
  AppAdminOrgsOrgIdUsersRoute: AppAdminOrgsOrgIdUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
