#!/bin/bash

echo "🗄️  MANUAL DATABASE MIGRATION GUIDE"
echo "===================================="
echo ""
echo "Since automated migration is having connectivity issues,"
echo "let's use the Supabase Dashboard method:"
echo ""
echo "📋 STEP-BY-STEP MIGRATION:"
echo ""
echo "1️⃣ EXPORT FROM STAGING:"
echo "   • Go to: https://supabase.com/dashboard/project/sbphmrjoappwlervnbtm"
echo "   • Navigate to: Table Editor"
echo "   • Click: 'Export' button (top right)"
echo "   • Select: 'Export all tables'"
echo "   • Download: staging_export.sql"
echo ""
echo "2️⃣ IMPORT TO PRODUCTION:"
echo "   • Go to: https://supabase.com/dashboard/project/ftiqmqrjzebibcixpnll"
echo "   • Navigate to: SQL Editor"
echo "   • Click: 'New query'"
echo "   • Paste the exported SQL content"
echo "   • Click: 'Run'"
echo ""
echo "3️⃣ VERIFY MIGRATION:"
echo "   • Check Table Editor in production"
echo "   • Verify all tables and data are present"
echo "   • Test login with superadmin user"
echo ""
echo "🔗 QUICK LINKS:"
echo "   🟡 Staging Dashboard:  https://supabase.com/dashboard/project/sbphmrjoappwlervnbtm"
echo "   🟢 Production Dashboard: https://supabase.com/dashboard/project/ftiqmqrjzebibcixpnll"
echo ""
echo "📊 EXPECTED TABLES TO MIGRATE:"
echo "   • employees"
echo "   • pay_groups"
echo "   • paygroup_employees"
echo "   • pay_runs"
echo "   • payslips"
echo "   • auth.users (superadmin)"
echo "   • All other payroll tables"
echo ""
echo "⚠️  IMPORTANT NOTES:"
echo "   • This method preserves all data and relationships"
echo "   • Superadmin user will be migrated with all permissions"
echo "   • All existing data will be preserved"
echo ""
echo "✅ After migration, your production app should work perfectly!"
