#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

// ANSI colors
const colors = {
  green: '\x1b[32m',
  red: '\x1b[31m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m',
  reset: '\x1b[0m',
  bold: '\x1b[1m'
};

function log(message, color = colors.reset) {
  console.log(`${color}${message}${colors.reset}`);
}

function loadEnvFile(filePath) {
  if (!fs.existsSync(filePath)) {
    return {};
  }
  
  const content = fs.readFileSync(filePath, 'utf8');
  const envVars = {};
  
  content.split('\n').forEach(line => {
    const trimmed = line.trim();
    if (trimmed && !trimmed.startsWith('#')) {
      const [key, ...valueParts] = trimmed.split('=');
      if (key && valueParts.length > 0) {
        envVars[key.trim()] = valueParts.join('=').trim().replace(/^["']|["']$/g, '');
      }
    }
  });
  
  return envVars;
}

function resolveTargetEnv() {
  const fromInput = String(process.env.TARGET_ENV || '').trim().toLowerCase();
  if (['production', 'staging', 'development'].includes(fromInput)) return fromInput;

  if (process.env.NODE_ENV === 'production') return 'production';
  return 'staging';
}

function loadEnvForTarget(targetEnv) {
  if (fs.existsSync('.env.next')) {
    return loadEnvFile('.env.next');
  }

  const targetFile =
    targetEnv === 'production' ? '.env.production'
      : targetEnv === 'staging' ? '.env.staging'
        : '.env.development';

  const files = ['.env', targetFile].filter(f => fs.existsSync(f));

  let envVars = {};
  for (const file of files) {
    envVars = { ...envVars, ...loadEnvFile(file) };
  }
  return envVars;
}

async function testSupabaseConnection() {
  log('\n🔗 SUPABASE CONNECTION TEST STARTING...', colors.bold + colors.blue);
  
  const targetEnv = resolveTargetEnv();
  const envVars = loadEnvForTarget(targetEnv);
  
  const supabaseUrl = envVars.VITE_SUPABASE_URL;
  const anonKey = envVars.VITE_SUPABASE_ANON_KEY;
  const serviceRoleKey = envVars.SUPABASE_SERVICE_ROLE_KEY;
  const usingServiceRole = Boolean(serviceRoleKey);
  const supabaseKey = usingServiceRole ? serviceRoleKey : anonKey;
  
  if (!supabaseUrl || !supabaseKey) {
    log('❌ Missing Supabase credentials', colors.red);
    return { success: false, error: 'Missing credentials' };
  }
  
  const environment = targetEnv.toUpperCase();
  
  log(`\n📋 Connection Details:`, colors.bold);
  log(`  • Environment: ${environment}`);
  log(`  • Supabase URL: ${supabaseUrl}`);
  log(`  • Auth mode: ${usingServiceRole ? 'SERVICE_ROLE' : 'ANON'}`);
  log(`  • API Key: ${supabaseKey.substring(0, 20)}...`);
  
  try {
    // Dynamic import for ES modules
    const { createClient } = await import('@supabase/supabase-js');
    
    const supabase = createClient(supabaseUrl, supabaseKey);
    
    log(`\n🧪 Testing connection...`, colors.yellow);
    
    // Test with a simple query
    const { data, error } = await supabase
      .from('employees')
      .select('id')
      .limit(1);
    
    if (error) {
      // If anon key is blocked by RLS/permissions, the DB is still reachable.
      // In that case we treat the connectivity check as a success.
      const message = String(error.message || '').toLowerCase();
      const looksLikeRls =
        message.includes('row level') ||
        message.includes('row-level') ||
        message.includes('rls') ||
        message.includes('permission denied') ||
        message.includes('not authorized') ||
        message.includes('unauthorized');

      if (!usingServiceRole && looksLikeRls) {
        log(`⚠️ Connection reachable but query blocked by permissions (RLS). Continuing as SUCCESS.`, colors.yellow);
        const statusReport = {
          timestamp: new Date().toISOString(),
          environment,
          supabaseUrl,
          connectionStatus: 'SUCCESS_WITH_PERMISSION_RLS',
          testQuery: 'employees table',
          recordsFound: 0,
          error: null
        };

        fs.writeFileSync('SUPABASE_STATUS.md', `# Supabase Connection Status

## Test Results
- **Timestamp**: ${statusReport.timestamp}
- **Environment**: ${statusReport.environment}
- **Status**: ✅ ${statusReport.connectionStatus}
- **Test Query**: ${statusReport.testQuery}
- **Records Found**: ${statusReport.recordsFound}

---
*Generated by automated Supabase connection test*
`);

        log(`\n📄 Status report saved to: SUPABASE_STATUS.md`);
        return { success: true, data: statusReport };
      }

      log(`❌ Connection failed: ${error.message}`, colors.red);
      return { success: false, error: error.message };
    }
    
    log(`✅ Connection successful!`, colors.green);
    log(`  • Query returned: ${data ? data.length : 0} records`);
    
    // Create status report
    const statusReport = {
      timestamp: new Date().toISOString(),
      environment,
      supabaseUrl,
      connectionStatus: 'SUCCESS',
      testQuery: 'employees table',
      recordsFound: data ? data.length : 0,
      error: null
    };
    
    fs.writeFileSync('SUPABASE_STATUS.md', `# Supabase Connection Status

## Test Results
- **Timestamp**: ${statusReport.timestamp}
- **Environment**: ${statusReport.environment}
- **Status**: ✅ ${statusReport.connectionStatus}
- **Test Query**: ${statusReport.testQuery}
- **Records Found**: ${statusReport.recordsFound}

## Connection Details
- **Supabase URL**: ${statusReport.supabaseUrl}
- **Test Table**: employees
- **Query**: SELECT id FROM employees LIMIT 1

---
*Generated by automated Supabase connection test*
`);
    
    log(`\n📄 Status report saved to: SUPABASE_STATUS.md`);
    
    return { success: true, data: statusReport };
    
  } catch (error) {
    log(`❌ Connection test failed: ${error.message}`, colors.red);
    
    const statusReport = {
      timestamp: new Date().toISOString(),
      environment,
      supabaseUrl,
      connectionStatus: 'FAILED',
      error: error.message
    };
    
    fs.writeFileSync('SUPABASE_STATUS.md', `# Supabase Connection Status

## Test Results
- **Timestamp**: ${statusReport.timestamp}
- **Environment**: ${statusReport.environment}
- **Status**: ❌ ${statusReport.connectionStatus}
- **Error**: ${statusReport.error}

---
*Generated by automated Supabase connection test*
`);
    
    return { success: false, error: error.message };
  }
}

// Run the test
testSupabaseConnection()
  .then(result => {
    if (result.success) {
      log(`\n✅ Supabase connection test completed successfully!`, colors.green + colors.bold);
      process.exit(0);
    } else {
      log(`\n❌ Supabase connection test failed!`, colors.red + colors.bold);
      process.exit(1);
    }
  })
  .catch(error => {
    log(`\n💥 Unexpected error: ${error.message}`, colors.red + colors.bold);
    process.exit(1);
  });
