#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

// ANSI colors
const colors = {
  green: '\x1b[32m',
  red: '\x1b[31m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m',
  reset: '\x1b[0m',
  bold: '\x1b[1m'
};

function log(message, color = colors.reset) {
  console.log(`${color}${message}${colors.reset}`);
}

function loadEnvFile(filePath) {
  if (!fs.existsSync(filePath)) {
    return {};
  }
  
  const content = fs.readFileSync(filePath, 'utf8');
  const envVars = {};
  
  content.split('\n').forEach(line => {
    const trimmed = line.trim();
    if (trimmed && !trimmed.startsWith('#')) {
      const [key, ...valueParts] = trimmed.split('=');
      if (key && valueParts.length > 0) {
        envVars[key.trim()] = valueParts.join('=').trim().replace(/^["']|["']$/g, '');
      }
    }
  });
  
  return envVars;
}

async function testSupabaseConnection() {
  log('\n🔗 SUPABASE CONNECTION TEST STARTING...', colors.bold + colors.blue);
  
  // Load environment variables
  const envFiles = ['.env', '.env.local', '.env.production', '.env.staging'];
  let envVars = {};
  
  for (const file of envFiles) {
    if (fs.existsSync(file)) {
      envVars = { ...envVars, ...loadEnvFile(file) };
    }
  }
  
  const supabaseUrl = envVars.VITE_SUPABASE_URL;
  const supabaseKey = envVars.VITE_SUPABASE_ANON_KEY;
  
  if (!supabaseUrl || !supabaseKey) {
    log('❌ Missing Supabase credentials', colors.red);
    return { success: false, error: 'Missing credentials' };
  }
  
  // Determine environment
  let environment = 'UNKNOWN';
  if (supabaseUrl.includes('kctwfgbjmhnfqtxhagib')) {
    environment = 'PRODUCTION';
  } else if (supabaseUrl.includes('sbphmrjoappwlervnbtm')) {
    environment = 'STAGING';
  }
  
  log(`\n📋 Connection Details:`, colors.bold);
  log(`  • Environment: ${environment}`);
  log(`  • Supabase URL: ${supabaseUrl}`);
  log(`  • API Key: ${supabaseKey.substring(0, 20)}...`);
  
  try {
    // Dynamic import for ES modules
    const { createClient } = await import('@supabase/supabase-js');
    
    const supabase = createClient(supabaseUrl, supabaseKey);
    
    log(`\n🧪 Testing connection...`, colors.yellow);
    
    // Test with a simple query
    const { data, error } = await supabase
      .from('employees')
      .select('id')
      .limit(1);
    
    if (error) {
      log(`❌ Connection failed: ${error.message}`, colors.red);
      return { success: false, error: error.message };
    }
    
    log(`✅ Connection successful!`, colors.green);
    log(`  • Query returned: ${data ? data.length : 0} records`);
    
    // Create status report
    const statusReport = {
      timestamp: new Date().toISOString(),
      environment,
      supabaseUrl,
      connectionStatus: 'SUCCESS',
      testQuery: 'employees table',
      recordsFound: data ? data.length : 0,
      error: null
    };
    
    fs.writeFileSync('SUPABASE_STATUS.md', `# Supabase Connection Status

## Test Results
- **Timestamp**: ${statusReport.timestamp}
- **Environment**: ${statusReport.environment}
- **Status**: ✅ ${statusReport.connectionStatus}
- **Test Query**: ${statusReport.testQuery}
- **Records Found**: ${statusReport.recordsFound}

## Connection Details
- **Supabase URL**: ${statusReport.supabaseUrl}
- **Test Table**: employees
- **Query**: SELECT id FROM employees LIMIT 1

---
*Generated by automated Supabase connection test*
`);
    
    log(`\n📄 Status report saved to: SUPABASE_STATUS.md`);
    
    return { success: true, data: statusReport };
    
  } catch (error) {
    log(`❌ Connection test failed: ${error.message}`, colors.red);
    
    const statusReport = {
      timestamp: new Date().toISOString(),
      environment,
      supabaseUrl,
      connectionStatus: 'FAILED',
      error: error.message
    };
    
    fs.writeFileSync('SUPABASE_STATUS.md', `# Supabase Connection Status

## Test Results
- **Timestamp**: ${statusReport.timestamp}
- **Environment**: ${statusReport.environment}
- **Status**: ❌ ${statusReport.connectionStatus}
- **Error**: ${statusReport.error}

---
*Generated by automated Supabase connection test*
`);
    
    return { success: false, error: error.message };
  }
}

// Run the test
testSupabaseConnection()
  .then(result => {
    if (result.success) {
      log(`\n✅ Supabase connection test completed successfully!`, colors.green + colors.bold);
      process.exit(0);
    } else {
      log(`\n❌ Supabase connection test failed!`, colors.red + colors.bold);
      process.exit(1);
    }
  })
  .catch(error => {
    log(`\n💥 Unexpected error: ${error.message}`, colors.red + colors.bold);
    process.exit(1);
  });
